apiVersion: v1
kind: Pod
metadata:
  name: girus
  labels:
    run: girus
spec:
  containers:
  - name: nginx
    image: nginx
  - name: apache
    image: bitnami/apache
    ports:
    - containerPort: 8082
  dnsPolicy: ClusterFirst
  restartPolicy: Always
